version: '3'
services:
  diploma:
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: 'php artisan serve --host=0.0.0.0 --port=8000'
    ports:
      - 8000:8000
    build:
      context: ./
      dockerfile: ./Dockerfile
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: diploma
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3307
    expose:
      - 3307
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
volumes:
  diploma:
  db:
